### ISSUE TITLE
Comparison with Workerman

### ISSUE THREAD

**Issue by raghuveer** [symplely/coroutine#3]
While Swoole, ReactPHP, AmPhp etc async libraries are covered along with other programming languages like Go, Python and others in terms of coroutine implementation that is done in this project, I am interested to see symplely/coroutine library compared with Workerman as well @techno-express 

https://github.com/walkor/Workerman

thank you

With Best Regards
Raghuveer

**Comment by techno-express** [comment]
Not sure if I can give it justice. 

1. There are no CI tests, what proof the package/project even works? Where are the examples to run to try things out?
2. This package here is **not a framework**, it tries to show a *standard/simple* way to write **native** asynchronous code. The other **PHP** packages I compare, just require too much setup. I make distinct different in development of a library to actually using it.

I believe i came across **Workerman** before, when I started to rewrite this **forked** and renamed project. 
Actually, I started with the other **PHP** packages to just use, and discovered to much setup to do simple stuff, not like other languages usage.

I have now put **Workerman** on my watch list. I could try using it for my web-socket implementation.
I have reviewed some of it's code base, and seen the documentation. It's network specific where this library is general purpose.

**Comment by raghuveer** [comment]
Thank you for the quick response and for the attempt to analyse Workerman as well.

personally while I thought to use Workerman and it's phpsocketio (https://github.com/walkor/phpsocket.io) when implementing a hosted websocket service, I finally went with Ratchet (http://socketo.me/), Custom wrappers of Amphp based MySQL & Redis libraries in my implementation that came out well, actually there is no wrong with Workerman but I felt it easy to work with Ratchet and subsequently with Amphp as I found some documentation and examples for the latter.

thank you

With Best Regards
Raghuveer

**Comment by techno-express** [comment]
I think we are talking about two different things, this library is **not a framework!** 
It does not present itself as such. This library allows you to write in a certain way, you would need to provide the actual code. You would build your own framework. 

I have no control how others wish to promote there own work, that alternative link is just such, shouldn't even be listed there.

**Comment by raghuveer** [comment]
agree with your views, I just shared what I came across today.
