### ISSUE TITLE
can we get symplely/coroutine benchmarked?

### ISSUE THREAD

**Issue by raghuveer** [symplely/coroutine#4]
I am following the web framework benchmarks (https://github.com/the-benchmarker/web-frameworks) of different web frameworks, routers and combinations

example: 

1) swoole with laravel/slim/symfony etc...
2) workerman based frameworks etc...

results can be found at https://web-frameworks-benchmark.netlify.app/result

can we get symplely/coroutine benchmarked as well?

I remember seeing Workerman as top entry for weeks, then others taking the position, even today, a workerman based micro framework "mark (https://github.com/passwalls/mark)" stays in position 2

we can make a benchmark request here: https://github.com/the-benchmarker/web-frameworks/issues

please share your thoughts @techno-express 

thank you

With Best Regards
Raghuveer

**Comment by techno-express** [comment]
I would need to write a framework first. 
I could write a example script that could for fill the benchmark request.

**Comment by raghuveer** [comment]
an example script for the benchmark will surely help, that might add more users & contributors with similar wavelength too to the project.

thank you

**Comment by raghuveer** [comment]
created the example script @techno-express? a quick reminder and request, thank you
