### ISSUE TITLE
about php 8.1 based fiber support in Symplely coroutine

### ISSUE THREAD

**Issue by raghuveer** [symplely/coroutine#5]
Hi,

As php 8.1 is public few weeks earlier, any plan to support fiber implementation in php 8.1?

https://wiki.php.net/rfc/fibers

In this context, are we going to integrate https://github.com/revoltphp/event-loop or php fibers directly?

please share your inputs

thank you

**Comment by TheTechsTech** [comment]
I know this is way too late, been working on many different things. 

But anyway, it seems you really haven't looked into the code or read anything, You would have found my opinion of that, not good. I'm on a different path. There is no plans, no desire whatsoever. Besides, the feature has all ready been implemented, But not the way you what, a framework, you will not find it here. 

There is a tests Fibers folder here having there tests, but not using any of the code, just the function signatures are the same.

There is no need for Fibers to exists, by the way implemented or RFC claims it suppose to resolve, to be nice it only rehash `yield` with a different name, but you need to understand the science behind that too. Some people using PHP actually studied compute science.

**Comment by raghuveer** [comment]
I always aspired to integrate your coroutine library as part of my micro framework. After trying the examples on your github page, tried amphp based http client, mysql & redis libraries & reactphp based websocket library for an application back in 2021 and later tried integrating workerman library in my php framework, that was partly successful then.

Thanks a lot, for sharing your inputs :)
