### ISSUE TITLE
can this utility be run in a set it and forget it format? 

### ISSUE THREAD

**Issue by halukkaramete** [symplely/coroutine#6]
Let me explain. 
In my PHP page, I'd like to start a process and NOT wait for an answer. All I'm interested in that lengthy process to start in another URL. A trigger so to speak. 

Currently, when you engage an API call or call functions like file-get_contents(), the current script has to stop and wait for that particular statemet/api to finish. And that slows down the current script. 

Can we do somethig like this with your tool? 

quick.php 

do stuff 
initiate longtask.php?param1=value1    // this line should be async but furthermore, when I'm done with dia/exit below, longtask can still continue without affecting the die time. 
continue doing stuff
die & exit.

**Comment by TheTechsTech** [comment]
Seems, your question more general beginner programming help issue. 

Also you haven't looked over the examples, the question has been answered and that is a tiny part of what you can do.
